### ISSUE TITLE
CUDA OOM when training 3D VQ-VAE for CTs

### ISSUE THREAD

**Issue by max-3l** [samb-t/x2ct-vqvae#2]
I'm currently trying to reproduce your results for the chest X-Ray to CT generation.

When training the 3D VQ-VAE the VRAM of my NVIDIA A100 with 80 GB VRAM is not sufficient. In your paper, you stated that you trained the VQ-VAEs also on A100s. However, just doing a rough estimation, even one intermediate representation after the first Conv3D with a depth of 16 and a batch size of 6 allocates (6 x 16 x 256 x 256 x 256 x 16 bits) 3.2 GB. Even a few layers fill up the memory during the gradient calculation. To train the CT VQ-VAE I used the recently updated configuration `default_ct_chest_8x8x8_config.py`.  Setting the batch size to 1 and using gradient accumulation also produces an out of memory failure.

Am I using the correct configuration? 
Did you use more than one GPU per model, or maybe a CT size, different to the 256 x 256 x 256 stated in the ReadMe?

**Comment by abrilcf** [comment]
Hi, sorry I confused the size of the original data and after processing. We used a size of 128 x 128 x 128 for chest CTs. I'll update the readme, thanks!!
