### ISSUE TITLE
Train details about 3dvqgan

### ISSUE THREAD

**Issue by CrazyLi15** [samb-t/x2ct-vqvae#3]
Hi,

 thanks for sharing this awesome work and release of the source code!

I encountered some difficulties while training vqgan_3d in my own dataset that the decoder of vqgan_3d still can not generate sufficiently similar images，even after training for 400 epochs.

To train the vqgan_3d I also used the recently updated configuration default_ct_chest_8x8x8_config.py but incautiously turned “depthwise_block” to  “resblock”.

Would it be possible for you to share the pretrained checkpoints as well?

**Comment by abrilcf** [comment]
Hi,

thank you for your interest in our work!

The repo has been updated. You can now find the link to our pre-trained models in the instructions. I'd suggest cloning the repo again, as the code was cleaned up and reorganised for clarity. 

Can you provide more details about your dataset (e.g., size, type of images, etc)?

Thanks!

**Comment by CrazyLi15** [comment]
Thank you for the update!

My dataset consists of 324 4D CT scans of 12 patients, with dimensions of (128,128,128)，which are processed using data augmentation and resampling methods. Each 4D CT scan sequence contains images of 10 phases.

Thanks again for your suggestion and sharing！

**Comment by abrilcf** [comment]
Hi, in our work the goal is to obtain a 3D representation conditioned on 2D images. In your case, you have each scan containing a sequence of 10 phases, making 4D. I assume you're increasing the number of channels to account for this in the architecture, meaning (B, 10, 128, 128, 128)? Or you wish to somehow translate from 2D to 4D?

**Comment by CrazyLi15** [comment]
Apologies for the earlier confusion.

I separated 10 distinct CT scans from each 4D CT sequence, with each CT representing a phase image. In other words, 3240 3D CT scans are considered as input to the architecture in my case, with dimensions of (B, 1, 128, 128, 128).

I hope this clarifies the issue! Wishing you happy holidays in advance if you're celebrating! 😊
